apiVersion: v1
kind: Pod
metadata:
  name: gameoflife-mysql
spec:  
  containers:
    - name: mysql-cont
      image: mysql:8
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-volume
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'rootroot'
        - name: MYSQL_DATABASE
          value: 'gameoflife'
        - name: MYSQL_USER
          value: qtdevops
        - name: MYSQL_PASSWORD
          value: qtdevops
      ports:
        - name: mysqlport
          containerPort: 3306
          protocol: TCP
  volumes:
    - name: mysql-volume
      persistentVolumeClaim:
        claimName: gameoflife-vloume