apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: gameoflife-vloume
spec:
   accessModes:
     - ReadWriteOnce
   storageClassName: managed-premium
   resources:
     requests: 
       storage: 1Gi
      
  