apiVersion: v1
kind: Service
metadata:
  name: gameoflife-services
spec:
  type: LoadBalancer
  selector:
    name: gameoflife-application
  ports:
     - name: gameoflife
       targetPort: 8080
       port: 35000